title: Harlee Scordo
description: Data Science Portfolio
##logo: /assets/img/headshot4.jpg
# websites: https://www.datascienceportfol.io/dashboard
# websites: www.linkedin.com/in/harleescordo
show_downloads: true
google_analytics: 
##theme: jekyll-theme-time-machine
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
