title: Harlee Scordo
logo: /assets/img/headshot4.jpg
# websites: https://www.datascienceportfol.io/dashboard
# websites: www.linkedin.com/in/harleescordo
show_downloads: true
theme: jekyll-theme-minimal
